name: setup
description: Setup docker and jar
inputs:
  jar:
    description: "setup jar"
    default: 'false'
    required: false
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: test-target
        path: .
    - shell: bash
      working-directory: ./assets
      run: cp -r ./java/* ./
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_buildx: false
    - if: inputs.jar == 'true'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '8'
    - if: inputs.jar == 'true'
      shell: bash
      working-directory: ./assets
      run: jar cvf assets.war suo5.jsp suo5.jspx
