// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultSuo5Config() {
  return window['go']['main']['App']['DefaultSuo5Config']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function RunSuo5WithConfig(arg1) {
  return window['go']['main']['App']['RunSuo5WithConfig'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
