// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ctrl} from '../models';
import {main} from '../models';

export function DefaultSuo5Config():Promise<ctrl.Suo5Config>;

export function GetStatus():Promise<main.Status>;

export function RunSuo5WithConfig(arg1:ctrl.Suo5Config):Promise<void>;

export function Stop():Promise<void>;
