// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {suo5} from '../models';
import {main} from '../models';

export function DefaultSuo5Config():Promise<suo5.Suo5Config>;

export function ExportConfig(arg1:suo5.Suo5Config):Promise<void>;

export function GetStatus():Promise<main.Status>;

export function ImportConfig():Promise<suo5.Suo5Config>;

export function RunSuo5WithConfig(arg1:suo5.Suo5Config):Promise<void>;

export function Stop():Promise<void>;
