// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultSuo5Config():Promise<any>;

export function GetStatus():Promise<any>;

export function RunSuo5WithConfig(arg1:any):Promise<void>;

export function Stop():Promise<void>;
